import os
Import('env')

#rapidapp lib
frame_src = Glob('*.cpp')
frame_src += Glob('../utils/*.c')
frame_src += Glob('../utils/*.cpp')
frame_src += Glob('../coroutine/*.cpp')

static_lib = env.StaticLibrary('rapidapp', frame_src)
Install('../lib', static_lib)
