import os
Import('env')

game_env = env.Clone()
game_env.Append(CPPPATH=['../../', '../../utils/', './'])
game_env.Append(LIBPATH=['../../'])

os.system('echo \'genereate c++ code over protobuf [ball_game_cs.proto]...\' && protoc --cpp_out=. ball_game_cs.proto')
game_src = Glob('*.cpp')
game_src += Glob('*.cc')
game_src += Glob('../../lib/librapidapp.a')
game_env.Program('logicsvr', game_src, LIBS=['event', 'glog', 'gflags', 'protobuf', 'pthread'])


